INFRA-268 add auth in admin cluster
m10-payments/workflow-templates pull request #110
Opened 2023-08-29 12:29 UTC by victor-khilin-m10

2023-08-30 11:18 UTC, anatoliy-polivin-m10 requested changes

2023-08-30 11:18 UTC, anatoliy-polivin-m10 commented on .github/workflows/workflow_pr.yml
> +    uses: m10-payments/workflow-templates/.github/workflows/reusable_integration_tests.yml@feat/INFRA-268_auth-in-admin
Сначала PR с изменениями, потом проставления тегов, потом PR с обновлением версий
```suggestion
    uses: m10-payments/workflow-templates/.github/workflows/reusable_integration_tests.yml@v1.25.3
```

2023-08-30 11:18 UTC, anatoliy-polivin-m10 commented on .github/workflows/workflow_pr.yml
> +    uses: m10-payments/workflow-templates/.github/workflows/reusable_destroy_feature_env.yml@feat/INFRA-268_auth-in-admin
То же самое
```suggestion
    uses: m10-payments/workflow-templates/.github/workflows/reusable_destroy_feature_env.yml@v1.21.0
```

2023-08-30 11:19 UTC, anatoliy-polivin-m10 commented
Нужно добавить в комментарии ссылки на успешные тестовые прогоны `feature-env`, `pr-validation`, `destroy-env` пайплайнов

2023-08-30 11:22 UTC, anatoliy-polivin-m10 commented on .github/workflows/workflow_pr.yml
> +    uses: m10-payments/workflow-templates/.github/workflows/reusable_integration_tests.yml@feat/INFRA-268_auth-in-admin
Вообще я обхожу этот процесс иногда: навешиваю тег на своей фиче ветке, ставлю правильные версии в PR, а после мерджа перевешиваю тег с фиче ветки на мастер. Но в таком случае есть даунтайм

2023-08-30 11:31 UTC, victor-khilin-m10 commented on .github/workflows/workflow_pr.yml
> +      ARGOCD_ADM_PASSWORD:
да, забыл подчистить.
В будущем просто изменим ARGOCD_PASSWORD на secret.ARGOCD_ADM_PASSWORD

2023-08-30 13:59 UTC, victor-khilin-m10 commented
https://github.com/m10-payments/backend-template-service/pull/485 - PR


https://github.com/m10-payments/backend-template-service/actions/runs/6025688047 - feature env
https://github.com/m10-payments/backend-template-service/actions/runs/6025608719 - PR validation; destroy env

2023-08-30 14:05 UTC, anatoliy-polivin-m10 commented
> [m10-payments/backend-template-service#485](https://github.com/m10-payments/backend-template-service/pull/485) - PR
> 
> https://github.com/m10-payments/backend-template-service/actions/runs/6025688047 - feature env https://github.com/m10-payments/backend-template-service/actions/runs/6025608719 - PR validation; destroy env

pr не считается. `run checks` запускает пайплайн из дефолтной ветки, т.е. тебе надо было прям в мастере в `backend-template-service` указать свою ветку в версии `pr-validation`

2023-08-31 13:00 UTC, victor-khilin-m10 commented
https://github.com/m10-payments/backend-template-service/actions/runs/6037310845

2023-08-31 14:21 UTC, anatoliy-polivin-m10 commented on .github/workflows/workflow_pr.yml
> +    uses: m10-payments/workflow-templates/.github/workflows/reusable_integration_tests.yml@v2.1.0
Тега `v2.1.0` нет в `workflow-templates`

2023-08-31 14:23 UTC, anatoliy-polivin-m10 commented on .github/workflows/workflow_feature.yml
> +          cp /home/runner/.kube/config $GITHUB_WORKSPACE/admin_k8s
Почему в предыдущем шаге `Set terraform var` не указывается путь до кубконфига?

2023-08-31 14:28 UTC, anatoliy-polivin-m10 commented on .github/workflows/reusable_destroy_feature_env.yml
> +      backend_adm_cluster_name:
Еще есть предложение переименовать эту переменную. Я правильно понимаю, что одна переменная с кластером используется для указания EKS кластера, в котором крутятся сервисы, для которых запускается пайплайн, а другая для argocd? Может кластер с арго обозвать `argocd_cluster_name`?

2023-08-31 14:35 UTC, victor-khilin-m10 commented on .github/workflows/workflow_pr.yml
> +    uses: m10-payments/workflow-templates/.github/workflows/reusable_integration_tests.yml@v2.1.0
После мержа сразу же тег навешу

2023-09-01 07:13 UTC, anatoliy-polivin-m10 approved these changes

2023-09-01 07:14 UTC, merged